### ISSUE TITLE
[DOC]: Testing issue open workflow

### ISSUE THREAD

**Issue by user-lfdsystems** [lfdsystems/testing-workflows#5]

**Comment by admin-lfdsystems** [comment]
Dear **user-lfdsystems**,

Thank you for opening an Issue.

Please make sure you have provided as much context as possible.

We will review this as soon as possible.

We will keep you posted with the progress.

>[!Warning]
>Be careful if you modify the Issue at any moment then it will reset the review process and will be marked as new.
