### ISSUE TITLE
Testing issue open steps instead of jobs

### ISSUE THREAD

**Issue by user-lfdsystems** [lfdsystems/testing-workflows#72]

**Comment by admin-lfdsystems** [comment]
**user-lfdsystems**,

Thank you for submitting an Issue.

Please make sure you habe provided as much context as possible.

We will review this as soon as possible.

We will keep you posted with the progress.

>[!Note]
>_If you make any changes to the Issue's body or title, the review process will reset and the Issue will be moved to the New state_.
